---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ikygoose.
--- DateTime: 1/4/2021 9:10 PM
---

os.loadAPI("moveAPI.lua")

local tArgs = {...}

local depth = tonumber(tArgs[1])
local width = tonumber(tArgs[2])
local height = tonumber(tArgs[3])

local slot = 1

local function placeDepth()
    for d = 1, depth do
        selectItem()
        turtle.placeDown()
        moveAPI.move( moveAPI.FORWARD, 1)
    end
end

local function placeWidth()
    for w = 1, width do
        selectItem()
        turtle.placeDown()
        moveAPI.move( moveAPI.FORWARD, 1)
    end
end

local function selectItem()
    while turtle.getItemCount( slot ) == 0 do
        local s = 1

        while s <= 16 and turtle.getItemCount( slot ) == 0 do
            slot = ( slot % 16 ) + 1
            turtle.select( slot )
        end

        if turtle.getItemCount( slot ) == 0 then
            print("Add Blocks!")
            local event, p1 = os.pullEvent("turtle_inventory")
        end
    end
end

for h  = 1, height do
    moveAPI.move(moveAPI.UP, 1)
    placeDepth()
    moveAPI.turn(moveAPI.RIGHT)
    placeWidth()
    moveAPI.turn(moveAPI.RIGHT)
    placeDepth()
    moveAPI.turn(moveAPI.RIGHT)
    placeWidth()
    moveAPI.turn(moveAPI.RIGHT)
end

